### ISSUE TITLE
Wizdler not loading request for WSDL

### ISSUE THREAD

**Issue by Ankita-0607** [pepri/wizdler#17]
My wsdl is getting loaded in browser but when I click on request it is giving me following error:
No global type was found: {undefined}string

**Comment by pepri** [comment]
This issue will be fixed in few next days.

**Comment by pepri** [comment]
Fixed in 1.28.

**Comment by Ankita-0607** [comment]
Issue is still the same.. May I know when 1.28 will be deployed ?

**Comment by Ankita-0607** [comment]
It is working now..Thank you very much :)

**Comment by Ankita-0607** [comment]
Hi.. Please confirm if HTTP URL wsdl will work or not.. bcs for wsdl having http URL it is still not working..
